#include "glutils.h"
AMN_NAMESPACE_OPEN_SCOPE

GLuint SCREENSPACEQUAD_VERTEX_SHADER    = 0;
GLuint SCREENSPACEQUAD_FRAGMENT_SHADER  = 0;
GLuint SCREENSPACEQUAD_PROGRAM_SHADER   = 0;
GLuint SCREENSPACEQUAD_VAO              = 0;
GLuint SCREENSPACEQUAD_VBO              = 0;

AMN_NAMESPACE_CLOSE_SCOPE
