#include "glutils.h"
PXR_NAMESPACE_OPEN_SCOPE

extern GLuint SCREENSPACEQUAD_VAO = 0;
extern GLuint SCREENSPACEQUAD_VBO = 0;
extern GLuint SCREENSPACEQUAD_VERTEX_SHADER = 0;
extern GLuint SCREENSPACEQUAD_FRAGMENT_SHADER = 0;
extern GLuint SCREENSPACEQUAD_PROGRAM_SHADER = 0;

PXR_NAMESPACE_CLOSE_SCOPE
